# Generated by Django 2.2.5 on 2019-10-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20191013_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_from_timetable',
            field=models.BooleanField(default=False),
        ),
    ]
